### ISSUE TITLE
[Feature] Anonymous Transactions

### ISSUE THREAD

**Issue by asdfghjz** [nanocurrency/raiblocks#1103]
**Feature**: Fully Decentralized Opt-In Anonymous Transactions

**Comment by rkeene** [comment]
Let's move this discussion into #1101 which is regarding a similar feature.

**Comment by asdfghjz** [comment]
@rkeene It actually, isn't. #1101 is specific to zk-snarks this is in general opt-in privacy transactions. I would appreciate if this post could be reopened. :)

**Comment by jmmcgee** [comment]
I haven't fully thought it through, but I also think that conditional payments as proposed in #1670 could allow for something like a [CoinJoin](https://en.bitcoin.it/wiki/CoinJoin) in Nano. I'm not sure how useful this would be in increasing privacy since Nano is account-based and coin-join's don't change who controls an account, but maybe the added edges could obfuscate analysis? 

The basic idea is to have a ring of conditional payments (through accounts 1,2,...,N,1) that commitment atomically. I don't really have the scheme fully flushed out, but it the beginning of the idea is something like hashlocks for routing payments through intermediaries in Bitcoin LN.
- account N generates a random number hashes it, reveals the hash to account 1
- account 1 generates a payment to 2 conditional upon the hash commitment.
- account 2 generates a payment to 3 conditional upon the same hash commitment,
- etc. forward to N.
- N reveals the secret to N-1 (and the network), finalizing his payment.
- N-1 reveals the secret to N-2 (and the network), finalizing his payment. 
- etc. backwards to 1

I haven't yet figured out how to modify this scheme to ensure that account N also pays account 1.
