### ISSUE TITLE
please make the status make sense for the average technical user

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [nanocurrency/raiblocks#1245]
![image](https://user-images.githubusercontent.com/16560332/46257232-4d6dbd00-c4f1-11e8-8f83-6601053c2581.png)

Is my node synced or not? I have no idea, it just stays at 2624

I never understood the thing that's in the parenthesis... when you hover over it, it says "Blocks downloaded".... then why does it go down in time, shouldn't it go up, as more blocks are downloaded?

So is my node synced or not?

**Comment by pedfx** [comment]
Your node receives new blocks - on the parenthesis - but it needs to check if it's a valid block to save it on the ledger, so the number after "Block:" is the counter of saved blocks.

Your node can be considered synced if the checked blocks counter is similar to other nodes, you can only compare it to know. An easy option is to use `curl https://mynano.ninja/api/blockcount` at the terminal, but since you're using the GUI you can check it using https://www.nanode.co/blocks 

I do agree, though it's not something hard to understand, the description should be more didactic for starters than "block count (blocks downloaded)".

On RPC use: 
<img width="774" alt="captura de tela 2018-09-30 as 09 28 00" src="https://user-images.githubusercontent.com/12234380/46257765-65afee80-c495-11e8-8bda-78e3fbc2eb83.png">
