### ISSUE TITLE
Wallet and node in Linux download no longer Programs but shared libraries.

### ISSUE THREAD

**Issue by BlackBeltBob** [nanocurrency/raiblocks#1252]
Hi,

I used to be able to run the wallet by downloading the Linux tar.bz2 file, then extracting it to where I wanted it. As of v16.1, the linux file's two programs, rai_node and nano_wallet are no longer working as programs, but are of type: shared library (application/x-sharedlib). Is this intended? I checked the full release notes, but found no mention of it.

**Comment by Morty-C-137** [comment]
same here, can't execute nano_wallet 16.1 on ubuntu. 
CLI Error Message:
./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by ./nano_wallet)
./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./nano_wallet)
./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./nano_wallet)
./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./nano_wallet)

**Comment by rkeene** [comment]
The change from a non-shared object to a shared object is a result of the binaries being compiled on a newer version of Ubuntu than previous binary tarballs.  Previous binary tarballs were compiled on Ubuntu 16.04 (Xenial) while this release they were compiled on the latest Ubuntu LTS release (v18.04; Bionic).  The defaults for this release of Ubuntu are to include Position Independent Executables (PIEs) which are shared objects.  This change (from non-PIE to PIE) has no bearing on the fact that the functionality of the executables _per se_, but the change of build platform that precipitated this change (Ubuntu 16.04 -> Ubuntu 18.04) also caused the "nano_wallet" executable to be linked against versioned symbols which cannot be found in older versions of `libQt5Core.so.5` and `libQt5Widgets.so.5` and that is the reason the programs won't run on older versions of Ubuntu.

The ultimate solution we are going to provide is to release packages for each platform specifically rather than a binary tarball that does not indicate its dependencies.

We are tracking this working Issue #12.

**Comment by rkeene** [comment]
This should be resolved in the binary releases provided in V16.2, which were compiled on Ubuntu 16.04.

I'm going to close this issue based on this solution but please let me know if you have further issues !
