### ISSUE TITLE
Unable to receive pending funds

### ISSUE THREAD

**Issue by altmank** [nanocurrency/raiblocks#233]
Hello, 

Installed RAI Desktop Wallet, created password and backed up seed. Got account address and sent some XRB to it. It was very far out of sync and even after days of running non-stop it did not catch up even though it's installed on SSD and fast network. I downloaded latest ldb and replaced. I then imported my wallet using seed. After import my previous account address is no longer shown in the wallet. The accounts page does however show my pending deposit in the Wallet Pending section. The use of the more recent ldb allowed my local wallet to finish syncing with the blocks, still no change in accepting my funds and again I still cannot see the original account address in the GUI wallet.

As a troubleshooting step I started using RPC commands. Account list shows the original account address, it shows the pending funds but attempting to run a receive command on the transcation returns this:
{
    "block": "0000000000000000000000000000000000000000000000000000000000000000"
}

Any ideas?

**Comment by michaeljs1990** [comment]
Were you able to resolve this issue?

**Comment by altmank** [comment]
No, it is still an issue and the funds are unable to be received using the
desktop wallet. Seems like a severe bug.

**Comment by clemahieu** [comment]
Can you hop in to chat.discord.net #support?

Is your wallet unlocked?  It sounds like you already pushed "Create Account" to get your account back in the list after restoring the seed.  If it's unlocked and the account shows in your list it should retrieve any pending balances.

As long as you have your seed and it generates the account you have funds it you'll be able to spend your balance once the issue is fixed.

**Comment by altmank** [comment]
Hi clemahieu, I messaged you privately in Discord.

**Comment by embatbr** [comment]
How do I know if my transaction is still pending? In my account the balance is shown, but if I see in raiblocks.net, with shows my transactions as "pending deposits" and the amount sent also as "pending deposits".

Should I create a receive transaction manually or the desktop wallet does it automatically (since it is also a fullnode)? There is no "receive" button, only a "send" one.

**Comment by dansksun** [comment]
Hi,

I have the same problem (with the desktop wallet),  & I do hold the Seed.
It says status: Synchronizing, Block:314257 (4367774)  

Here is block link:
https://raiblocks.net/block/index.php?h=C21DA6DFFB7A88CB07C426158D674CD2D20B437A2CD3940C6D67E55CBAC48ACD

Is it because I sent only 1 coin? 
Any help is appropriated. 

Thanks -:)
Dansk

**Comment by embatbr** [comment]
@dansksun in my case the wallet is synchronized. I downloaded the ledger instead of sync from the beginning. But still, mine is with pending deposits.

**Comment by embatbr** [comment]
I just sent 1 XRB from one account to another (both mine). My wallet balance is altered (precious value minus 1) and the destination account show 1 XRB. Still, the changes weren't spreaded out to the network.

**Comment by dansksun** [comment]
Hi @embatbr,

Do you have a link to ledger and instructions how to sync it ?

Thanks -:)

**Comment by embatbr** [comment]
Solved. The wallet wasn't actually synced (even with all blocks).
When will the light wallet be available (for desktops)?

**Comment by embatbr** [comment]
@dansksun https://yadi.sk/d/fcZgyES73Jzj5T

**Comment by dansksun** [comment]
Thanks @embatbr,

I fallowed the explanation in the link you sent me ( https://yadi.sk/d/fcZgyES73Jzj5T).

Now wallet says 👍 
status: Synchronizing, Block: 4688610 (10141)

And numbers are still changing.

2 questions: 
a. When this sync will finish, do you assume that this will fix my wallet and then I will be abler to see the transfer?
b. How long did that process to for you?

Any other insight will be much appreciated.

Thanks,
Dansk

**Comment by embatbr** [comment]
I guess so. Mine solved this way, but was not as fast as I expected. I just caught a flight now and stayed some hours away, so my wallet was synchronizing again. Now it is "Running", with the name in black (instead of blue) and with no number between parenthesis (downloaded and not processed).

I changed my representative and I am waiting this change to be shown in the network, with the pending deposit.

**Comment by embatbr** [comment]
@clemahieu could you clarify this question? Am I right in my explanation or am I missing some step?

**Comment by embatbr** [comment]
@dansksun did it solved fast? When you see your account in raiblocks.net, it shows as pending deposit or receive?

**Comment by dansksun** [comment]
I fallowed the explanation in the link you sent me ( https://yadi.sk/d/fcZgyES73Jzj5T).

first  wallet notification was:
status: Synchronizing, Block: 4688610 (10141)

After 5 min wallet wallet notification changed to :
status: Synchronizing, Block: 4702188

and I see my coin. Problem solved.
Thanks you -:)

To 
https://raiblockscommunity.net

**Comment by dansksun** [comment]
to @clemahieu 
If you have any contact with this website https://raiblockscommunity.net (that is down at the moment), you'd better add clearer comments how to fix this issue, because with XRB so popular it's just a matter of time and you will get lots of people with same issues... 
Thanks for amazing coin

**Comment by embatbr** [comment]
I guess my representative is receiving to many transactions to spread and this may be taking too much time.

**Comment by Kryptobrother** [comment]
I have the same problem. How can I really tell if my wallet is 100% synchronized? For me the status is: Running, Block: 4706649 (19).

**Comment by michaeljs1990** [comment]
If you are unsure if your wallet is synced you can always check https://raiblocks.net/ it has the current block count within around 10 blocks on the front page. That should be the first thing you check. Additionally none of the issues above is an actual bug and these conversations should be moved to https://forum.raiblocks.net/ which has a section for technical support and all of this is already answered.

Additionally https://www.reddit.com/r/RaiBlocks/wiki/index is also a good resource and answers these issues.

**Comment by stefonarch** [comment]
I had the same issue with git checkout from 2 days ago: in rai_wallet 2 transactions were ok and received, but in explorer shown as "pending". In the blockviewer using advenced> account viewer and using the hash I could see a "receive" block but "rebroadcast" was greyed out, using insert block > process no result. 
Upgraded to last git checkout and I was able to rebroadcast one of the "receive" blocks and immediately solved for both transactions. 
The problem was that only watching the wallet one does not even see that tere are pending transactions.
