### ISSUE TITLE
Error upgrading to v9.0 from v8.0: Disk images could not be opened

### ISSUE THREAD

**Issue by pramttl** [nanocurrency/raiblocks#236]
I tried upgrading from 8.0 to 9.0 with 8.0 version on my Mac installed. I see the following error when I try to install 9.0 pre-release:

<img width="369" alt="screen shot 2017-12-16 at 6 40 17 pm" src="https://user-images.githubusercontent.com/933802/34076127-9f476be2-e290-11e7-9619-c78b2caa2715.png">

**Comment by pramttl** [comment]
Also, are there any instructions on upgrading ? E.g. Do I have to uninstall v 8.0 before I upgrade to 9.0 or will it overwrite the necessary files while keeping encrypted private key, etc intact.

**Comment by jamescoxon** [comment]
I've got the same error - we think that its because the default file system now for cmake has changed - Colin is going to review it and see if he can use the old default.

To upgrade just overwrite the app, the data.ldb file is kept separately in Application Support. However I do recommend you back up your seed as you can recover your funds when the world ends...
