### ISSUE TITLE
Limiting bandwidth on Raiblocks wallets (or peers)

### ISSUE THREAD

**Issue by bitoiu** [nanocurrency/raiblocks#255]
Hey folks :wave:

I've used the 8.0 wallet for a while and had no issues running it on my laptop. When I updated to 9.0RC3 and used the Linux index from the wiki to get it up to date, it seems like all peers out there are leeching my wallet to an extreme. I have no problem with that, I in fact want that, but not to the point where that sucks my whole connection, preventing me to do anything else. It picks at 1.5MB/s upload. I've tried the following so far:

- Looked through wallet settings to limit peers but there doesn't seem to be one.
- Looked at this repo's wiki to see if there's a command line argument for peer limit or bandwidth limit but didn't find one.
- Googling on how to limit bandwith on a single port on High Sierra doesn't seem trivial, but should be possible. 

Before going into the woods with this option, is there any lower cost option to be able to run the wallet in a way that it doesn't suck the life out of my internet :blush:

:octocat::heart:

**Comment by straightwhiteproud** [comment]
Can always use netlimiter until the devs implement a setting

**Comment by bitoiu** [comment]
Hi @straightwhiteproud :wave:

On MacOS I don't think there's NetLimiter, App Dev Tools have a product that allows you to throttle the network but only for the whole adapter and not a port. I've found some examples with `ipfw`:

```
sudo ipfw add 100 pipe 1 tcp from 0.0.0.0/32 to 0.0.0.0/32 7075
sudo ipfw pipe 1 config bw 4Mbps
```

Will test this shortly and get back to folks that might be having the same issue 

:octocat::heart:

**Comment by GoneUp** [comment]
A general peer limit would be really a good start.

**Comment by stefonarch** [comment]
Similar here, my node on a linode is running few day but has already used 21% of monthly bandwidth (1T/MONTH).

**Comment by learnforpractice** [comment]
Yes,I think It’s a useful feature. Bandwidth can be limited base on balance hold by account.And it can also give some protect from network attack.

**Comment by rkeene** [comment]
Bandwidth reductions for the protocol are part of vote-by-hash, vote-stapling, and ultimately node stratification identified in issue #1092.

Many other mitigations for bandwidth over-use have also been implemented, such as limiting the number of peers that a node allows bootstrapping from concurrently.

I don't think a coarse bandwidth limitation fits into the node itself, although many platforms support implementing that at a higher layer if that is still desired in the form of traffic shaping or traffic policing.

I'm going to close this ticket so that we can track the work on the specific items mentioned above directly and not a more general item.  Let me know if there are additional questions.
