### ISSUE TITLE
Are spelling mistakes considered bugs? [QUESTION]

### ISSUE THREAD

**Issue by reteps** [nanocurrency/raiblocks#335]
If I find a spelling mistake, can that be considered a bug and be eligible for a minor bug bounty of 10XRB?

**Comment by androm3da** [comment]
No.

Don't you think that's bordering on ludicrous?

IMO the bounties were not defined clearly enough.  Clarifications I have heard since seem to indicate that only bugs in the protocol's design are eligible.  But it's still not quite clear I think.

One thing is clear: typos and spelling errors aren't eligible

**Comment by reteps** [comment]
Great, glad to hear. I was looking into #302 and #307 and just wanted to be sure. The only good way to find a bug would be an error or thorough testing though, right?
