### ISSUE TITLE
Proposition: Split the blockchain in more files

### ISSUE THREAD

**Issue by ejpcmac** [nanocurrency/raiblocks#368]
The blockchain is currently stored in one big file. This has on major drawback: more it grows, and more it is difficult to backup, as it needs to be entirely copied each time a backup is done.

Using multiple files like Bitcoin Core does is a great approach to this issue: only last the last file is modified, until is reaches its maximum size. Older files are immutable.

The blocks could be store in raw format in those files, and an index could be store in a database.

**Comment by Marc477** [comment]
Would be nice too that it prioritize your own blockchain and the blockchain of pending transaction sending to you. So that you can sign receiving without having the whole thing.

**Comment by rkeene** [comment]
This will be implemented as part of ledger pruning (#1094) as a part of the on-going effort to enable node stratification (#1092).

Additionally, as part of epoch blocks many blocks will be split into a different database table which will have some improvements for delta-based backup systems.

I'm going to close this ticket since on-going projects will resolve it in a more specific way.
