### ISSUE TITLE
Where's the Beta version ?

### ISSUE THREAD

**Issue by EvertonMelo** [nanocurrency/raiblocks#491]
according to the Roadmap:
https://raiblocks.net/media/raiblocks-roadmap-v2-en.png
( official site raiblocks, by @jamescoxon  )

5fh line: 
December 2017 / 

and in column "Core"

> "Beta test for mobile wallet, Release of Mobile Wallet" 

I would like to know where I can information about this status in github? 

in the main directory there is only one version:
font: https://github.com/clemahieu/raiblocks/milestones

see in the case of the BITCOIN CORE project:
font: https://github.com/bitcoin/bitcoin/milestones
Contains the versions:
- Stable: >=v0.15.2
- Beta: v0.16.x v0.17.x
- Alpha: Future ( Undefined future version )

would not it be interesting to use an established model? 

I would like to contribute as BETA-Tester, 
but I find it very chaotic to have no version distinction.
download the latest version is to say that the project did not learn with errors, does not properly maintain the legacy versions.

I ask you to understand my criticism in a constructive way, I have raised only logical arguments.

please reply to me by referencing the source code of the project, processes, blogs, word of Devs ... they are not source code .. even if they are in the communication channels of the project, please inform me referring to github.

**Comment by NaelsonDouglas** [comment]
Just to move the issue, there's this tweet where @zackshapiro says he's testing the IOS mobile wallet

https://twitter.com/ZackShapiro/status/951196541074788354

**Comment by EvertonMelo** [comment]
@NaelsonDouglas 

it may not have been clear, but the point is:

how can tests be performed without an environment for this?

will tests be performed in the production environment? Is this serious? same?

Is this really a good practice ???

in the Bitcoin Core project there is Testnet:
https://en.bitcoin.it/wiki/Testnet

In what environment are the tests performed?

would you have it possible to clarify:

"First iOS Wallet TestFlight Goint to Out" by Zack Shapiro.

seems conclusive to many involved in the project, but note:

https://www.reddit.com/r/RaiBlocks/comments/7mu3rv/raiblocks_testnet_tools/

See the dates, the Raiblocks testnet exists ???

because in the domains:

https://www.raiblocks.club/block/testnet

https://github.com/clemahieu

https://github.com/clemahieu/raiblocks/wiki

@clemahieu  

information on it,

is it possible to believe in the tests of an unofficial test environment?

Is not that biased?

or would not it be interesting to have access to the source code and be able to audit everything independently?
or even contribute to improvements?

I do not understand how a project can be so obscure and not be questioned for it.

where is the iOS Wallet source code? how can we know if it does not have the Backdoor inside the Wallet, since the code is not open?

**Comment by PlasmaPower** [comment]
Yeah there's a test network, you can use it by passing cmake `-DACTIVE_NETWORK=rai_test_network`.

The development version of raiblocks is just the master branch, stable releases are tagged in Git and on raiblocks.net

**Comment by zackshapiro** [comment]
Hey guys. How's it going.

Here's the latest on the iOS wallet:

It's currently in a private repo on my GitHub. It's almost ready for primetime, got some more testing to do and then we're going to release it. We're going to get an independent security audit done (which can include the community as well) before we open-source the code. 

It's not currently using the testnet. It uses the mainnet 

We're running a little behind schedule from the old roadmap because we've had a pretty crazy last six weeks or so.

LMK if you have other questions.

Thanks

**Comment by EvertonMelo** [comment]
@PlasmaPower  Are we talking about the same project?

if so, would you like to tell me how you already know that there is no documentation for Testing, so reading the CMACK of the project does not say much, badly to know if it is an environment or if you are throwing everything to **%LOCALHOST%**

`set_target_properties (core_test slow_test PROPERTIES COMPILE_FLAGS "${PLATFORM_CXX_FLAGS} ${PLATFORM_COMPILE_FLAGS} -DQT_NO_KEYWORDS -DACTIVE_NETWORK=${ACTIVE_NETWORK} -DRAIBLOCKS_VERSION_MAJOR=${CPACK_PACKAGE_VERSION_MAJOR} -DRAIBLOCKS_VERSION_MINOR=${CPACK_PACKAGE_VERSION_MINOR} -DBOOST_ASIO_HAS_STD_ARRAY=1")`

how would you inform me referencing Github or even a project documentation?

**Comment by PlasmaPower** [comment]
@EvertonMelo If you're talking about this repository, then yes, we're talking about the same project.

Documentation is definitely something we need to work on. If you're looking to run the tests, I'd recommend looking at the CI (Continuous Integration) scripts: https://github.com/clemahieu/raiblocks/blob/master/ci/build-travis.sh#L24

The important flags there for testing are: `-DACTIVE_NETWORK=rai_test_network -DRAIBLOCKS_TEST=ON -DRAIBLOCKS_GUI=ON`

**Comment by Saemy1** [comment]
@zackshapiro I also interested to review and/or support the development of the ios app.

**Comment by EvertonMelo** [comment]
@zackshapiro 
@PlasmaPower 

Update for your roadmap.

![raiblocks-roadmap-v2 2-en](https://user-images.githubusercontent.com/7637553/36276011-b0356fae-1273-11e8-9a57-b896cc2de6ec.png)

**Comment by comeback** [comment]
You meant December 2018.  Not December 2022.

**Comment by EvertonMelo** [comment]
@comeback 

only a question, was the project delivered on this date?
ask for the @zackshapiro  show where the binaries are?

did you understand why this date?

**Comment by EvertonMelo** [comment]
@clemahieu 

Thank you for your posture unprofessional.

- closes a questioning without even giving the status of it.
- ignores direct questioning is complacent with lies

Thank you very much for confirming what I expected.

**Comment by AyiSoli** [comment]
Betas are released few weeks ago so its closed

**Comment by EvertonMelo** [comment]
@AyiSoli 

**before you run away like everyone else has.
read the whole topic:**

according to the Roadmap:
https://raiblocks.net/media/raiblocks-roadmap-v2-en.png
( official site raiblocks, by @jamescoxon  )

5fh line: 
December 2017 / 

and in column "Core"

> "Beta test for mobile wallet, Release of Mobile Wallet" 


I would like to know where I can information about this status in github? 

in the main directory there is only one version:
font: https://github.com/clemahieu/raiblocks/milestones


see in the case of the BITCOIN CORE project:
font: https://github.com/bitcoin/bitcoin/milestones
Contains the versions:
- Stable: >=v0.15.2
- Beta: v0.16.x v0.17.x
- Alpha: Future ( Undefined future version )

would not it be interesting to use an established model? 

I would like to contribute as BETA-Tester, 
but I find it very chaotic to have no version distinction.
download the latest version is to say that the project did not learn with errors, does not properly maintain the legacy versions.

I ask you to understand my criticism in a constructive way, I have raised only logical arguments.

please reply to me by referencing the source code of the project, processes, blogs, word of Devs ... they are not source code .. even if they are in the communication channels of the project, please inform me referring to github.

**Comment by clemahieu** [comment]
We have enough beta testers. Thanks for asking.

**Comment by EvertonMelo** [comment]
@kvrban 

hi
the page: 
[
Desktop/Mobile Wallets](https://developers.nano.org/roadmap/desktop-mobile-wallets/)
- has no links for verification( on github ) 
- has no status ( nowhere ) 
Call it whatever you want. who knows 2022 you come the.


> Soure for wallets will be available on release. AFAIK Beta wallet binary you get on nano.org "Download our apps"
**Fonts Please.** 
the links you sent do not mention that.

> Or you check the source for a popular third party NANO wallet "Canoe" https://github.com/getcanoe The better place for this general topics are on https://www.reddit.com/r/nanocurrency/ or http://chat.nano.org/ 

_so, there is no prohibition anywhere. It's allowed, whether you like it or not._

Why do not you like to respond in places where everyone has access? 
Fear? 

note that I asked those same questions to @zackshapiro  and he had a better posture than yours.

**Comment by EvertonMelo** [comment]
@Saemy1 

he answered you 4 months later but replied.

really what is easy it does, which requires more it is omitted.

**Comment by zackshapiro** [comment]
The code will be open source when it’s on the App Store so that others
don’t fork and submit the app.

Thanks

Best,
Zack


On May 14, 2018 at 12:25 PM, Everton Melo <notifications@github.com> wrote:


which is difficult it does not:

but topic is outdated, but there is still no test environment, outside
documentation.

You're right, you better change the subject.
talk about would have implied doing something .. #correct @clemahieu
<https://github.com/clemahieu>

@ NaelsonDouglas

it may not have been clear, but the point is:

how can tests be performed without an environment for this?

will tests be performed in the production environment? Is this serious?
same?

Is this really a good practice ???

in the Bitcoin Core project there is Testnet:
https://en.bitcoin.it/wiki/Testnet

In what environment are the tests performed?

would you have it possible to clarify:

"First iOS Wallet TestFlight Goint to Out" by Zack Shapiro.

seems conclusive to many involved in the project, but note:

https://www.reddit.com/r/RaiBlocks/comments/7mu3rv/raiblocks_testnet_tools/

See the dates, the Raiblocks testnet exists ???

because in the domains:

https://www.raiblocks.club/block/testnet

https://github.com/clemahieu

https://github.com/clemahieu/raiblocks/wiki

*@clemahieu <https://github.com/clemahieu> ( direct mention 17 Jan 2018 )*

information on it,

is it possible to believe in the tests of an unofficial test environment?

Is not that biased?

or would not it be interesting to have access to the source code and be
able to audit everything independently?
or even contribute to improvements?

I do not understand how a project can be so obscure and not be questioned
for it.

where is the iOS Wallet source code? how can we know if it does not have
the Backdoor inside the Wallet, since the code is not open?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nanocurrency/raiblocks/issues/491#issuecomment-388878055>,
or mute the thread
