### ISSUE TITLE
rai_node stuck at milions unchecked blocks

### ISSUE THREAD

**Issue by stefonarch** [nanocurrency/raiblocks#580]
**Description of bug:**

Running latest git version for 4 days results in always 40'000 blocks missing and most of them unchecked:

> Current block: | 313870
> Number of unchecked blocks: | 5158034
> Number of peers: | 1579
> 

Number of checked blocks grow but yery slowly, ~37'000/day at this moment.
Ledger size is also growing to much: 8G

Probably those are addressed already here:
https://github.com/clemahieu/raiblocks/pull/566
https://github.com/clemahieu/raiblocks/pull/554#issuecomment-361317738

**Describe the results you received:**
No way setting up a working node in short time.

**Describe the results you expected:**
Setting up a new node should be fast.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
Linode qemu, ubuntu server 16.04 1gb ram
Single core Intel Xeon E5-2680 v3 (-MCP-) cache: 16384 KB bmips: 5001 speed: 2499 MHz (max)

**logs**
http://172.104.246.18/log.txt
This one endet also up with rai_node dead.

**Comment by PlasmaPower** [comment]
If you merge the two PRs you linked, does it work?

**Comment by lukealonso** [comment]
@PlasmaPower it needs one small change after both PRs are merged to work reliably, since they need to interact but I wasn't able to add the interaction in either one when they're standalone

**Comment by PlasmaPower** [comment]
Oh, I didn't know that. @stefonarch looks like you might have to wait or use a pre-synced DB.

**Comment by lukealonso** [comment]
@PlasmaPower It will *probably* work with both, certainly more likely than without, worth trying. The change I'm referring makes it so the bootstrap won't stop while there are unresolved forks pending.

**Comment by stefonarch** [comment]
Ok thanks, I'll try to upload a presynced db for the moment, when PR are committed I'll give it another try.

**Comment by stefonarch** [comment]
PS: I see with my poor connection it takes ~12 hours to upload, is there no compressed data.lzb available, similar to the yandex one (which does not work with wget)?

**Comment by elliottneilclark** [comment]
Can we get a new build on docker? Seems like the latest version on docker has the same issue.

**Comment by PlasmaPower** [comment]
@elliottneilclark which image are you using? Try `nanocurrency/nano`.

**Comment by elliottneilclark** [comment]
Yep that's what I'm using. been running since this morning

``
$ docker ps                                                                                                                                                CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS                                                                NAMES                                                                                                                                                          dcb85bffe272        nanocurrency/nano   "/bin/bash /entry.sh"   6 hours ago         Up 6 hours          0.0.0.0:7075->7075/tcp, 0.0.0.0:7075->7075/udp, ::1:7076->7076/tcp   epic_hamilton                                                                                                                                                                                                                                                                                                                       

$ curl -g -d '{ "action": "block_count" }' '[::1]:7076'                                                                                                    {                                                                                                                                                                         "count": "3108000",                                                                                                                                                   "unchecked": "2852593"                                                                                                                                            } 
``

**Comment by PlasmaPower** [comment]
@elliottneilclark that's built based on the latest commit: https://travis-ci.org/clemahieu/raiblocks/jobs/340343739#L3815

@lukealonso any idea why this is still happening?

**Comment by saitei** [comment]
I'm having the same issue.  Unchecked block count is continually rising, while the block count doesn't budge.  The block count has gone up by 1 block in the past 20 hours.

```
user@computer# curl -g -d '{ "action": "block_count"}' localhost:7076
{
    "count": "3108060",
    "unchecked": "365492"
}
```
I've also tried `bootstrap`, `bootstrap_any`, and `unchecked_clear` without success.  I'll try with a pre-synced db copy.

**Comment by stefonarch** [comment]
Don't see that anymore for weeks, closing.
