### ISSUE TITLE
Node services bulk pull requests during bootstrap

### ISSUE THREAD

**Issue by meltingice** [nanocurrency/raiblocks#812]
_This is somewhat conjecture but, after monitoring the logs..._

My node is still early on in the bootstrap process, yet it's servicing bulk pull requests from other nodes. Because there are a lot of unchecked blocks, it doesn't always know about the blocks in the bulk pull request so it sends everything instead. This seems pretty inefficient. Perhaps nodes shouldn't service bulk pulls during bootstrap?

For example:

```
[2018-04-17 18:19:53.283460]: Received bulk pull for F8615500C459AFC0BF8F59875D211B7ED4B58C3D210E10D46573D57A305E58EA down to 754A92B983D76B06850EC4F33046F35C8784C04934D7F018A9AE6CC6FE910558
[2018-04-17 18:19:53.283524]: Bulk pull end block doesn't exist: 754A92B983D76B06850EC4F33046F35C8784C04934D7F018A9AE6CC6FE910558, sending everything
```

**Comment by renesq** [comment]
May be related to https://github.com/nanocurrency/raiblocks/pull/553

**Comment by rkeene** [comment]
I think to avoid a situation where we reach bootstrapping deadlock, we should allow bulk pull requests to be processed while we are bootstrapping -- over time the situation should stabilize.  Lazy bootstrapping makes this situation more tenable as well, since it does `bulk_pull` on starting on a block hash rather than an account.  If the node it is bootstrapping from lacks this starting block hash, an empty set will be returned (and the node will search for a different peer to bootstrap from) rather than the entire account chain.

I think there's nothing to be done here, please re-open this ticket if you disagree -- thanks !
