### ISSUE TITLE
Could the network fail gracefully?

### ISSUE THREAD

**Issue by fallerOfFalls** [nanocurrency/raiblocks#990]
Bitcoin has many flaws but its fee system is very effective at preventing network spam, and it *keeps working* (albeit expensively) under load.

As we've seen from the recent spam attack, when the network can't cope, many nodes sort of go offline until they can catch up. To me this seems worse than a fee.

I'm aware that those bottlenecks are being addressed, but there will always be a bottleneck somewhere. So it's not a matter of whether the network capacity will be exceeded but when and how.

So I propose a "the network is under load" state. When nodes are unable to keep up, for whatever reason, they have a way of reaching a consensus that they are under load, and will operate differently until things return to normal.

When under load, there's a bidding war to get your transaction processed, just like Bitcoin. There could be a constantly adjusted fee option (users would have to manually choose this) or a constantly adjusting level of proof of work requirement (no pre-caching) so your transaction is sent when your proof of work reaches the threshold and otherwise keeps going (does that work? I don't know much about nonces) till it reaches the threshold.

Obviously you still would want to avoid this state. It's still a failure. This is just the backup, so that when failure happens, everything still works and nobody is stuck not being able to use the network at all.

**Comment by fallerOfFalls** [comment]
Uh, duplicate of #196

**Comment by clemahieu** [comment]
We have plans for a queueing mechanism weighted on (least recently used account) * (amount) * (PoW difficulty). Nodes will be able to dynamically increase the PoW difficulty they generate to get prioritization.

**Comment by fallerOfFalls** [comment]
Wow. That formula is just, genius. Just wow. I'm struggling to think of a scenario where it might not work well.

**Comment by kvrban** [comment]
On Reddit was a discussion about this topic to dynamically adjust the PoW
difficulty. Maybe some stimuli to find:
https://www.reddit.com/r/nanocurrency/comments/8y0ljp/what_is_the_incentive_to_spam_the_nano_network/e279oy7

My comment was: that any type of account based PoW adjustment could only
work, if open new accounts is more PoW expensive
then normal transactions. Otherwise a attacker just spam with new opened
accounts.
High PoW cost to open a new account should hit spammer harder, and not
normal Nano user, which use their accounts long-term.
